### PR TITLE
Minor improvements

### LINKED ISSUE #219: RGFW fails to compile with LLVM MinGW targeting Windows 11 on ARM64
When compiling RGFW on Windows 11 for ARM64 using [LLVM MinGW](https://github.com/mstorsjo/llvm-mingw) (llvm-mingw-20250613-ucrt-aarch64), the build fails with the following error:
`llvm-mingw-20250613-ucrt-aarch64/include/psdk_inc/intrin-impl.h:679:5: error: use of undeclared identifier '__builtin_ia32_sfence'`.

This originates from [this line](https://github.com/ColleagueRiley/RGFW/blob/ac95d8b3c07670992dc854618227ebe8f4975a69/RGFW.h#L374) in `RGFW.h`, where `_AMD64_` is manually defined. That macro leads Windows headers such as `xinput.h` to incorrectly assume x86-64 architecture, triggering inclusion of x86-specific intrinsics like `__builtin_ia32_sfence`.

This breaks compilation for ARM64 targets that do not support those intrinsics.

### PR DESCRIPTION
**Pull request by EimaMei**
Changes:
- Simplified `RGFW_BOOL` logic.
- Added a generic error code `RGFW_errNoMem`.
- Cleaned up some code to look nicer.
- Fixed a few minor spelling mistakes.
- Reworked `RGFW_window_initBuffer` make it less prone (assert, `RGFW_getScreenSize()` only gets called if the window is resizable) ~~as well as shorter~~ (NOTE: Due to C++ I couldn't turn the expression into a ternary operator and as such limited my contribution. Fix that. Please.)
- `RGFW_window_initBufferSize`has been reworked to include additional errors and to look nicer.
- Reworked `RGFW_setBit` with simpler logic and better naming (I'd suggesting renaming the function to `RGFW_maskSet`, but I digress).
- Removed a useless cast in `RGFW_window_initBufferPtr`.
- Improved some spacing.
- Some dead code elimination.
- Fixed the indenting nightmare in the Linux version of `RGFW_window_close`.
- Fixes #219.

### CODE REVIEW

File: RGFW.h [hunk 1]
```diff
@@ -364,21 +364,14 @@ int main() {
 #if defined(RGFW_X11) && defined(__APPLE__) && !defined(RGFW_CUSTOM_BACKEND)
 	#define RGFW_MACOS_X11
 	#define RGFW_UNIX
-	#undef __APPLE__
```
Comment (ColleagueRiley) [inline RGFW.h:367]: X11 on macOS should be tested before this is pulled.

File: RGFW.h [hunk 2]
```diff
@@ -364,21 +364,14 @@ int main() {
...
-	#if defined(_WIN64)
-		#define _AMD64_
-		#undef _X86_
-	#else
-		#undef _AMD64_
-		#ifndef _X86_
-			#define _X86_
-		#endif
-	#endif
+
```
Comment (ColleagueRiley) [inline RGFW.h:371]: This should be looked into later.

File: RGFW.h [hunk 3]
```diff
@@ -10892,7 +10883,6 @@ void RGFW_window_close(RGFW_window* win) {
 
 	if ((win->_flags & RGFW_WINDOW_ALLOC)) {
 	    RGFW_FREE(win);
-        win = NULL;
```
[the remark this answers is not in the document]
Comment (EimaMei) [reply RGFW.h:10895]: It's just dead code. Setting win to NULL does nothing as it just sets the pointer itself to NULL, not the contents of it.

Example:
```c
void some_func(RGFW_window* win) {
    win = NULL;
}

...
RGFW_window* win = 0x10;
some_func(win);
printf("%p", win); // still 0x10
```
